name             'cadmus'
maintainer       'Cymric'
maintainer_email 'mdavid626@gmail.com'
license          'All rights reserved'
description      'Installs/Configures cadmus'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
depends          'windows'
depends          'dotnetframework'
depends          'sql_server'
version          '0.1.0'
